### ISSUE TITLE
Übungsaufgaben

### ISSUE THREAD

**Issue by Marco5de** [ottojo/GRN#14]
Ich hab jetzt zu den meisten Übungsaufgaben mal was geschrieben, könnt ja mal drüber schauen ob das so passt und an ein paar Stellen (Unterschied GBN/SR und das DNS auflösen) fehlt auch noch was.

**Comment by swappad** [comment]
Checksumme bei C.3.U1 ist richtig

**Comment by swappad** [comment]
C.4.Ü1
C.4.Ü6
überprüft

**Comment by swappad** [comment]
B.4.Ü3 noch jeweils die IP von dem Mailserver abgefragt.
Bei Teilaufgabe 3 (zu github) war ich mir nicht ganz sicher. Könnt ihr ja mal anschauen
